"""Scheduled email digest service.

Generates and sends periodic email reports (daily P&L, weekly summary,
low stock alerts) to store owners/managers via SMTP.
"""

import logging
import os
import time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

logger = logging.getLogger(__name__)


class EmailDigestService:
    """Scheduled email digest generator and sender."""

    def __init__(self):
        self.smtp_host = os.environ.get("SMTP_HOST", "")
        self.smtp_port = int(os.environ.get("SMTP_PORT", "587"))
        self.smtp_username = os.environ.get("SMTP_USERNAME", "")
        self.smtp_password = os.environ.get("SMTP_PASSWORD", "")
        self.smtp_from = os.environ.get("SMTP_FROM", "noreply@retailos.app")
        self.use_tls = os.environ.get("SMTP_USE_TLS", "true").lower() == "true"
        self._digest_log: list[dict] = []

    @property
    def is_configured(self) -> bool:
        return bool(self.smtp_host and self.smtp_username)

    def _build_daily_digest_html(self, data: dict[str, Any]) -> str:
        revenue = data.get("revenue", 0)
        orders_count = data.get("orders_count", 0)
        top_products = data.get("top_products", [])
        low_stock = data.get("low_stock_items", [])
        pending_udhaar = data.get("pending_udhaar", 0)

        top_products_html = ""
        for p in top_products[:5]:
            top_products_html += f"<tr><td>{p.get('name', '')}</td><td>{p.get('qty_sold', 0)}</td><td>Rs.{p.get('revenue', 0):,.2f}</td></tr>"

        low_stock_html = ""
        for item in low_stock[:5]:
            low_stock_html += f"<tr><td>{item.get('name', '')}</td><td>{item.get('stock', 0)}</td><td>{item.get('days_left', 'N/A')}</td></tr>"

        return f"""
        <html>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: linear-gradient(135deg, #0d9488, #92400e); padding: 20px; border-radius: 12px; color: white; text-align: center;">
                <h1 style="margin: 0;">RetailOS Daily Digest</h1>
                <p style="margin: 5px 0 0;">Store Performance Summary</p>
            </div>

            <div style="background: #f8f9fa; padding: 20px; margin: 20px 0; border-radius: 8px;">
                <h2 style="color: #1a1a1a; margin-top: 0;">Today's Highlights</h2>
                <table style="width: 100%;">
                    <tr><td><strong>Total Revenue</strong></td><td style="text-align: right; font-size: 20px; color: #0d9488;">Rs.{revenue:,.2f}</td></tr>
                    <tr><td><strong>Orders</strong></td><td style="text-align: right; font-size: 20px;">{orders_count}</td></tr>
                    <tr><td><strong>Pending Udhaar</strong></td><td style="text-align: right; font-size: 20px; color: #dc2626;">Rs.{pending_udhaar:,.2f}</td></tr>
                </table>
            </div>

            <div style="margin: 20px 0;">
                <h3 style="color: #1a1a1a;">Top Selling Products</h3>
                <table style="width: 100%; border-collapse: collapse;">
                    <tr style="background: #e5e7eb;"><th style="padding: 8px; text-align: left;">Product</th><th>Qty</th><th>Revenue</th></tr>
                    {top_products_html if top_products_html else '<tr><td colspan="3" style="text-align: center; padding: 8px;">No sales data</td></tr>'}
                </table>
            </div>

            <div style="margin: 20px 0;">
                <h3 style="color: #dc2626;">Low Stock Alerts</h3>
                <table style="width: 100%; border-collapse: collapse;">
                    <tr style="background: #fee2e2;"><th style="padding: 8px; text-align: left;">Product</th><th>Stock</th><th>Days Left</th></tr>
                    {low_stock_html if low_stock_html else '<tr><td colspan="3" style="text-align: center; padding: 8px;">All stock levels OK</td></tr>'}
                </table>
            </div>

            <div style="text-align: center; padding: 20px; color: #6b7280; font-size: 12px;">
                <p>Generated by RetailOS v1.0.0</p>
            </div>
        </body>
        </html>
        """

    def _build_weekly_summary_html(self, data: dict[str, Any]) -> str:
        return f"""
        <html>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: linear-gradient(135deg, #0d9488, #92400e); padding: 20px; border-radius: 12px; color: white; text-align: center;">
                <h1 style="margin: 0;">RetailOS Weekly Summary</h1>
                <p style="margin: 5px 0 0;">Week of {data.get('week_start', 'N/A')}</p>
            </div>
            <div style="background: #f8f9fa; padding: 20px; margin: 20px 0; border-radius: 8px;">
                <table style="width: 100%;">
                    <tr><td><strong>Weekly Revenue</strong></td><td style="text-align: right;">Rs.{data.get('revenue', 0):,.2f}</td></tr>
                    <tr><td><strong>Total Orders</strong></td><td style="text-align: right;">{data.get('orders_count', 0)}</td></tr>
                    <tr><td><strong>New Customers</strong></td><td style="text-align: right;">{data.get('new_customers', 0)}</td></tr>
                    <tr><td><strong>Returns</strong></td><td style="text-align: right;">Rs.{data.get('returns_amount', 0):,.2f}</td></tr>
                    <tr><td><strong>Avg Order Value</strong></td><td style="text-align: right;">Rs.{data.get('avg_order_value', 0):,.2f}</td></tr>
                </table>
            </div>
            <div style="text-align: center; padding: 20px; color: #6b7280; font-size: 12px;">
                <p>Generated by RetailOS v1.0.0</p>
            </div>
        </body>
        </html>
        """

    async def send_digest(
        self,
        to_email: str,
        digest_type: str = "daily",
        data: dict[str, Any] | None = None,
    ) -> dict:
        data = data or {}

        if digest_type == "daily":
            subject = f"RetailOS Daily Digest - {time.strftime('%d %b %Y')}"
            html = self._build_daily_digest_html(data)
        elif digest_type == "weekly":
            subject = f"RetailOS Weekly Summary - Week of {data.get('week_start', time.strftime('%d %b'))}"
            html = self._build_weekly_summary_html(data)
        else:
            subject = f"RetailOS Report - {time.strftime('%d %b %Y')}"
            html = f"<html><body><pre>{data}</pre></body></html>"

        if self.is_configured:
            try:
                import aiosmtplib
                msg = MIMEMultipart("alternative")
                msg["Subject"] = subject
                msg["From"] = self.smtp_from
                msg["To"] = to_email
                msg.attach(MIMEText(html, "html"))

                await aiosmtplib.send(
                    msg,
                    hostname=self.smtp_host,
                    port=self.smtp_port,
                    username=self.smtp_username,
                    password=self.smtp_password,
                    use_tls=self.use_tls,
                )
                logger.info("Email digest sent to %s", to_email)
                entry = {"to": to_email, "type": digest_type, "subject": subject, "timestamp": time.time(), "status": "sent"}
                self._digest_log.append(entry)
                return {"status": "sent", "to": to_email, "subject": subject}
            except Exception as e:
                logger.warning("Email digest failed for %s: %s", to_email, e)
                return {"status": "error", "detail": str(e)}
        else:
            entry = {"to": to_email, "type": digest_type, "subject": subject, "timestamp": time.time(), "status": "demo", "html_length": len(html)}
            self._digest_log.append(entry)
            logger.info("Email digest (demo) to %s: %s", to_email, subject)
            return {"status": "sent_demo", "to": to_email, "subject": subject}

    def get_log(self, limit: int = 50) -> list[dict]:
        return self._digest_log[-limit:]


email_digest_service = EmailDigestService()
