"""initial schema

Revision ID: 50733d721f6c
Revises:
Create Date: 2026-04-05 15:19:42.112535

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '50733d721f6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
